(function(){
'use strict';
var V=(typeof vendetta!=='undefined'&&vendetta)||globalThis.vendetta||globalThis.revenge||globalThis.bunny||{};
var m=V.metro||{},c=m.common||{},R=c.React||g('createElement','useState')||globalThis.React,N=c.ReactNative||g('View','Text','Pressable')||{},ui=V.ui||{};
var root=(V.plugin&&V.plugin.storage)||V.storage||{};if(!root.channelMediaGalleryLite)root.channelMediaGalleryLite={};var S=root.channelMediaGalleryLite;
if(!Array.isArray(S.items))S.items=[];if(!S.filter)S.filter='all';if(!S.limit)S.limit=80;if(!S.channelId)S.channelId=null;
var timer=null,last='Ready';
function g(){try{return m.findByProps&&m.findByProps.apply(m,arguments)}catch(e){return null}}
function toast(x){last=String(x);try{(ui.toasts&&ui.toasts.showToast?ui.toasts.showToast:ui.showToast)(String(x))}catch(e){}try{console.log('[CMG]',x)}catch(e){}}
function arr(x){var o=[];if(!x)return o;if(Array.isArray(x))return x;try{if(Array.isArray(x._array))return x._array}catch(e){}try{if(x.toArray)return x.toArray()}catch(e){}try{if(x.forEach){x.forEach(function(v){if(v)o.push(v)});if(o.length)return o}}catch(e){}try{Object.keys(x).forEach(function(k){if(x[k])o.push(x[k])})}catch(e){}return o}
function curChan(){var names=['getChannelId','getLastSelectedChannelId','getCurrentlySelectedChannelId'];for(var i=0;i<names.length;i++){try{var mod=g(names[i]);if(mod&&typeof mod[names[i]]==='function'){var id=mod[names[i]]();if(id)return String(id)}}catch(e){}}return S.channelId||null}
function remember(){var id=curChan();if(id)S.channelId=id;return id}
function http(){var h=c.API||c.HTTP||g('get','post','put','del')||g('get','post','patch','del')||g('HTTP');return h&&h.get?h:null}
async function req(url,q){var h=http();if(!h)throw Error('No Discord HTTP module');var r=await h.get({url:url,query:q||{}});var b=r&&((r.body!==undefined&&r.body)||(r.data!==undefined&&r.data)||r);if(typeof b==='string')b=JSON.parse(b);if(b&&Array.isArray(b.messages))b=b.messages;if(!Array.isArray(b))throw Error('Bad HTTP response');return b}
function kindUrl(u,n,ct){u=String(u||'');n=String(n||'');ct=String(ct||'');var x=(u+' '+n+' '+ct).toLowerCase();if(/\.gif(\?|$)|image\/gif/.test(x))return'gif';if(/\.mp4|\.mov|\.webm|video\//.test(x))return'video';if(/\.png|\.jpe?g|\.webp|image\//.test(x))return'image';return null}
function add(out,seen,it,msg,type){var u=it.url||it.proxy_url||it.proxyURL;if(!u||seen[u])return;seen[u]=1;out.push({url:String(u),proxyUrl:it.proxy_url||it.proxyURL||u,thumbnailUrl:it.thumbnail&&it.thumbnail.url||it.thumbnail_url||u,type:type,name:it.filename||it.name||type,width:it.width,height:it.height,messageId:String((msg&&msg.id)||''),channelId:String((msg&&msg.channel_id)||S.channelId||''),author:msg&&msg.author&&(msg.author.username||msg.author.global_name)||'',time:msg&&msg.timestamp||''})}
function collect(msgs){var out=[],seen={};arr(msgs).forEach(function(msg){arr(msg.attachments).forEach(function(a){var t=kindUrl(a.url,a.filename,a.content_type);if(t)add(out,seen,a,msg,t)});arr(msg.embeds).forEach(function(e){if(e.image&&e.image.url)add(out,seen,e.image,msg,'embed');if(e.thumbnail&&e.thumbnail.url)add(out,seen,e.thumbnail,msg,'embed');if(e.video&&e.video.url)add(out,seen,e.video,msg,'video')})});return out}
async function scan(id,setItems,setMsg){id=String(id||remember()||'');if(!id){setMsg&&setMsg('Open a channel first');return}try{setMsg&&setMsg('Scanning '+id+'...');var msgs=[],before=null;for(var p=0;p<4&&msgs.length<S.limit;p++){var q={limit:Math.min(100,S.limit-msgs.length)};if(before)q.before=before;var page=await req('/channels/'+id+'/messages',q);if(!page.length)break;msgs=msgs.concat(page);before=page[page.length-1].id}var items=collect(msgs);S.channelId=id;S.items=items;S.savedAt=Date.now();setItems(items);setMsg&&setMsg('Saved '+items.length+' media');toast('Saved '+items.length+' media')}catch(e){var t=e&&e.message?e.message:String(e);setMsg&&setMsg(t);toast(t)}}
function pass(it,f){if(f==='all')return true;if(f==='pics')return it.type==='image';if(f==='videos')return it.type==='video';if(f==='gifs')return it.type==='gif';if(f==='embeds')return it.type==='embed';return true}
function open(it,setMsg){var v=g('openMediaModal')||g('openMediaViewer');var fn=v&&(v.openMediaModal||v.openMediaViewer);if(!fn){setMsg('Native media modal unavailable');return}var src=it.type==='video'?{videoURI:it.url,uri:it.thumbnailUrl||it.proxyUrl||it.url,width:it.width,height:it.height}:{uri:it.proxyUrl||it.url,width:it.width,height:it.height};try{Promise.resolve(fn({initialSources:[src],initialIndex:0,channelId:it.channelId,messageId:it.messageId})).catch(function(e){setMsg(e.message||String(e))})}catch(e){setMsg(e.message||String(e))}}
function onLoad(){try{remember()}catch(e){}try{if(timer)clearInterval(timer);timer=setInterval(function(){try{remember()}catch(e){}},1500)}catch(e){}toast('Channel Media Gallery lite loaded')}
function onUnload(){try{if(timer)clearInterval(timer)}catch(e){}timer=null;toast('Channel Media Gallery unloaded')}
function Settings(){if(!R||!N.View||!N.Text)return null;var View=N.View,Text=N.Text,Press=N.Pressable||N.TouchableOpacity,Scroll=N.ScrollView||View,Img=N.Image,Input=N.TextInput;var st=R.useState?R.useState(S.items||[]):[S.items,function(){}],items=st[0],setItems=st[1];var ms=R.useState?R.useState(last):[last,function(){}],msg=ms[0],setMsg=ms[1];var fs=R.useState?R.useState(S.filter):[S.filter,function(){}],f=fs[0],setF=fs[1];var cs=R.useState?R.useState(S.channelId||''):[S.channelId||'',function(){}],cid=cs[0],setCid=cs[1];function B(txt,cb,col){return Press?R.createElement(Press,{onPress:cb,style:{backgroundColor:col||'#5865f2',padding:12,borderRadius:10,marginTop:8,alignItems:'center'}},R.createElement(Text,{style:{color:'white',fontWeight:'800'}},txt)):null}function setFilter(x){S.filter=x;setF(x)}var shown=arr(items).filter(function(it){return pass(it,f)});return R.createElement(Scroll,{style:{padding:14}},R.createElement(Text,{style:{color:'white',fontSize:24,fontWeight:'900'}},'Channel Media Gallery Lite 1.1.21'),R.createElement(Text,{style:{color:'#aaa',marginTop:6}},'Current channel: '+(S.channelId||'none')+' • saved: '+arr(S.items).length),R.createElement(Text,{style:{color:'#ffb86b',marginTop:8}},String(msg||'')),Input?R.createElement(Input,{value:String(cid||''),onChangeText:function(t){S.channelId=t;setCid(t)},placeholder:'channel id optional',placeholderTextColor:'#777',style:{color:'white',borderColor:'#333',borderWidth:1,borderRadius:8,padding:10,marginTop:10}}):null,B('Scan Current / Channel ID',function(){scan(cid||S.channelId,setItems,setMsg)},'#5865f2'),B('Clear Pictures In Window',function(){setItems([]);setMsg('Window cleared; saved cache kept')},'#444'),R.createElement(View,{style:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:10}},['all','pics','videos','gifs','embeds'].map(function(x){return B(x,function(){setFilter(x)},x===f?'#43b581':'#333')})),R.createElement(Text,{style:{color:'#aaa',marginTop:10}},'Showing '+shown.length),R.createElement(View,{style:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:8}},shown.map(function(it,i){return Press?R.createElement(Press,{key:String(i),onPress:function(){open(it,setMsg)},onLongPress:function(){try{V.utils&&V.utils.clipboard&&V.utils.clipboard.setString(it.url);setMsg('Copied URL')}catch(e){}},style:{width:105,marginBottom:8}},Img?R.createElement(Img,{source:{uri:it.thumbnailUrl||it.proxyUrl||it.url},style:{width:105,height:105,borderRadius:8,backgroundColor:'#111'}}):R.createElement(Text,{style:{color:'white'}},it.type),R.createElement(Text,{style:{color:'#aaa',fontSize:11}},it.type)):null})));}
return{onLoad:onLoad,onUnload:onUnload,start:onLoad,stop:onUnload,settings:Settings,SettingsComponent:Settings};
})()
